### ISSUE TITLE
[Tracking issue] Add `MultiMaxSize` to all transactional state stores as needed

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/components-contrib#3016]
The `MultiMaxSize() int` method returns the maximum number of operations allowed in a transaction for the component. This is an optional method that is not (yet) part of the transactional state store interface.

We need to check all transactional state store components to see if they need this.

- [ ] CockroachDB
- [ ] etcd
- [ ] in-memory
- [ ] MongoDB
- [ ] MySQL/MariaDB
- [ ] Oracle Database
- [ ] PostgreSQL
- [ ] SQLite
- [ ] AWS DynamoDB
- [ ] MS SQL Server
- [ ] Oracle Cloud ATP
- [X] Azure Cosmos DB: #3015

**Comment by berndverst** [comment]
I have reviewed all state stores and done this.

The only ones that had limits were AWS Dynamo DB, ETCD, Azure CosmosDB.

#3094
#3093

**Comment by berndverst** [comment]
FYI @cgillum @DeepanshuA @RyanLettieri
