### ISSUE TITLE
Conformance Tests - Iteration 1 - Build Framework and API tests

### ISSUE THREAD

**Issue by mukundansundar** [dapr/components-contrib#404]
## Describe the proposal
Design and Build the framework for conformance tests for building blocks. 

RELEASE NOTE: N/A

**Comment by mukundansundar** [comment]
# Items to be done
- [ ]  Initial Set of conformance tests for State Pubsub and Secretstore (PR #586)
- [ ] Configure the conformance tests to run with template of component yml definitions
- [ ] Setup conformance tests for bindings. #409 (with Redis as sample)
- [ ] Create manually triggered workflow to run conformance tests #601 (with docker redis)
- [ ] Manually setup the following Azure Components to be used for conformance tests
  - [ ] Azure Service Bus #596 
  - [ ] Azure Event Grid #594 
  - [ ] Azure Blob Storage #593 
  - [ ] Azure CosmosDB #599 
  - [ ] Azure Storage Queue #595 
- [ ] Configure the conformance tests to run with the created Azure components (create template of component definitions and needed go code in test framework) will be done as part of the the setup tasks themselves
- [ ] Setup Kubernetes secret store conformance test #597 
- [ ] Setup MongoDB secret store conformance test 
- [ ] Setup and implement HTTP/HTTPS binding conformance test #598 
- [ ] Run conformance test workflow and verify

**Comment by mukundansundar** [comment]
@latest run https://github.com/dapr/components-contrib/actions/runs/572434473

All the runs: https://github.com/dapr/components-contrib/actions?query=workflow%3A%22Components+Conformance+Tests%22
